openapi: 3.0.1
info:
  title: Elite Wellness
  version: 0.0.2
  description: Admin API documentation

servers:
  - url: http://localhost:3333/admin
    description: Local API
  - url: http://stg.api.elitewellnessperformance.com:8090/admin
    description: Staging API

security:
  - token: []

paths:
  /scheduler/calendars:
    get:
      tags:
        - scheduler
      summary: list calendars
      responses:
        200:
          description: list of calendars
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Calendar'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/InternalError'

  /scheduler/calendars/:id/activities:
    get:
      tags:
        - scheduler
      summary: list activities associateds in calendar
      parameters:
        - in: path
          name: id
          required: true
          description: calendar id
          schema:
            type: string
      responses:
        200:
          description: list of calendars
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Activity'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/InternalError'

  /scheduler/appointments:
    get:
      tags:
        - scheduler
      summary: list appointments
      parameters:
        - name: calendars
          in: query
          required: true
          schema:
            type: array
        - name: date
          in: query
          required: true
          description: format ISO8601
          schema:
            type: string
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/InternalError'

components:
  # ---- security schemas
  securitySchemes:
    'token':
      type: http
      scheme: bearer
      bearerFormat: JWT

  # ---- responses
  responses:
    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'

  # ---- schemas
  schemas:
    ValidationError:
      type: object
      properties:
        message:
          type: string

    Error:
      type: object
      properties:
        message:
          type: string

    IdAndName:
      type: object
      properties:
        id:
          type: string
        name:
          type: string

    IdIntegerAndName:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    Activity:
      type: object
      properties:
        id:
          type: integer
          example: 4
        name:
          type: string
          example: Adult Training
        duration:
          type: integer
          example: 30

    Calendar:
      type: object
      properties:
        id:
          type: string
          example: 3500f32f-3e4a-4a42-88a4-31ad2c83bb09
        name:
          type: string
          example: Anthony
        minHoursToSchedule:
          type: number
          example: 12
        minHoursToCancel:
          type: number
          example: 12
        maxDaysInFuture:
          type: number
          example: 365
        maxEntryPerSlot:
          type: number
          example: 1
        createdAt:
          type: string
          example: 2022-02-10T23:40:36.370Z
        updatedAt:
          type: string
          example: 2022-02-10T23:40:36.370Z
        category:
          type: object
          properties:
            id:
              type: number
              example: 6
            name:
              type: string
              example: Categoria 1

    Appointment:
      type: object
      properties:
        id:
          type: string
        dateStart:
          type: string
        dateEnd:
          type: string
        calendarId:
          type: string
        calendarLabelId:
          type: string
        calendarClassId:
          type: string
        activity:
          allOf:
            - $ref: '#/components/schemas/IdIntegerAndName'
            - type: object
              properties:
                duration:
                  type: integer
        customer:
          $ref: '#/components/schemas/IdIntegerAndName'
        calendarLabel:
          allOf:
            - $ref: '#/components/schemas/IdAndName'
            - type: object
              properties:
                color:
                  type: string
        notes:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        canceledAt:
          type: string
