version: '3'

services:
  api:
    build: .
    image: wellness/api
    ports:
      - '3333:3333'
    volumes:
      - './.env:/usr/app/.env'
      - './google-cloud-key.json:/usr/app/google-cloud-key.json'
