version: '3'

services:
  db:
    container_name: wellness_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
    volumes:
      - ./db-volume:/var/lib/postgresql/data

  api:
    container_name: wellness_api
    build: .
    image: wellness/api
    ports:
      - 3333:3333
    volumes:
      - ./.env:/usr/app/.env
      - ./google-cloud-key.json:/usr/app/google-cloud-key.json
    depends_on: [db]
    command: sh -c "
      npm run migration:up
      && npm start
      "
