name: Production pipeline

on:
  workflow_dispatch:

env:
  SERVER: ${{ secrets.PRD_SERVER_HOST }}
  USER: ${{ secrets.PRD_SERVER_USER }}

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t wellness/api .
      - name: Export docker image
        run: docker save wellness/api | gzip > wellness_api.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: wellness_api_image
          path: wellness_api.tar.gz
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: wellness_api_image
      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.PRD_SERVER_HOST }}
      - name: Copy files to server
        run: |
          scp wellness_api.tar.gz $USER@$SERVER:/var/www/api.wellness.com
          scp docker-compose.yml $USER@$SERVER:/var/www/api.wellness.com
      - name: Load docker image in server
        run: >
          ssh $USER@$SERVER -t "
          cd /var/www/api.wellness.com;
          docker load -i wellness_api.tar.gz;
          rm wellness_api.tar.gz;"
      - name: Start docker container
        run: >
          ssh $USER@$SERVER -t "
          cd /var/www/api.wellness.com;
          docker-compose up -d;"
