name: Staging pipeline

on:
  workflow_dispatch:

env:
  SERVER: ${{ secrets.STG_SERVER_HOST }}
  USER: ${{ secrets.STG_SERVER_USER }}

jobs:
  build:
    needs: generate_config_files
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate config files
        run: |
          echo ${{secrets.STG_ENV_FILE}} >> .env
          echo ${{secrets.STG_GOOGLE_CLOUD_KEY}} >> google-cloud-key.json
      - name: Build docker image
        run: docker build -t wellness/api -f ./Dockerfile
      - name: Export docker image
        run: docker save wellness/api | gzip > wellness_api.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: wellness_api_image
          path: wellness_api.tar.gz
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: wellness_api_image
      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.STG_SERVER_HOST }}
      - name: Copy files to server
        run: |
          scp wellness_api.tar.gz $USER@$SERVER:/www/wellness/api
          scp docker-compose.yml $USER@$SERVER:/www/wellness/api
      - name: Load docker image in server
        run: >
          ssh $USER@$SERVER -t "
          cd /www/wellness/api;
          docker load -i wellness_api.tar.gz;
          rm wellness_api.tar.gz;"
      - name: Start docker container
        run: >
          ssh $USER@$SERVER -t "
          cd /www/wellness/api;
          docker-compose -p wellness up -d;"
